server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://10.255.72.216:10086/eureka/
spring:
  application:
    name: zuul-test
feign:
  hystrix:
    enabled: true
zuul:
  host:
    socket-timeout-millis: 2000
    connect-timeout-millis: 2000
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-client
    api-b:
      path: /api-b/**
      serviceId: feign-client
