server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://10.255.72.216:10086/eureka/
spring:
  application:
    name: feign-client
feign:
  hystrix:
    enabled: true
  # 压缩
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
turbine:
  app-config: feign-client
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false，false表示只对get请求生效,true则是所有的请求
  ReadTimeout: 1000   #负载均衡超时时间，默认值5000 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 1000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对重试负载均衡其他的实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms

feign.hystrix.enabled: true